group: mws_vision_bench
task:
  - mws_vision_bench_validation
metadata:
  version: 0.0
  sys_prompt: "Выберите правильный ответ из предложенных вариантов."
  gpt_eval_model_name: "gpt-3.5-turbo-0613"
